name: Deploy to Firebase Hosting on PR

'on': pull_request

jobs:
  build_and_preview:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v3

      - name: Set up API base URL
        run: echo "REACT_APP_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> $GITHUB_ENV
      
      - name: Set up google analytics tracking id
        run: echo "REACT_APP_GA_TRACKING_ID=${{ secrets.GA_TRACKING_ID }}" >> $GITHUB_ENV

      - run: npm ci && npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BAYITABROAD_JKAK }}'
          projectId: bayitabroad-jkak
